In [1]:
x = ["India", 1947, "Delhi", 200]
x

['India', 1947, 'Delhi', 200]

In [9]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [10]:
x.append("karnataka")
x

['Karnataka',
 'Independence',
 'Karnataka',
 200,
 'Delhi',
 1947,
 'India',
 'Independence',
 'Independent',
 'karnataka']

In [11]:
# strip cases
y = "19M"
a = y.rstrip("M")
int(a)

19

In [12]:
x[3]

200

In [13]:
x[1:3]

['Independence', 'Karnataka']

In [14]:
len(x)

10

In [18]:
t = ("RP", 12, "Mysuru")
t

('RP', 12, 'Mysuru')

In [19]:
# Dictionary - Key:Value
d1 = {"id":101, "name": "India", "Age": 200, "City":"Delhi"}
d1

{'id': 101, 'name': 'India', 'Age': 200, 'City': 'Delhi'}

In [20]:
d1['name']

'India'

In [21]:
d1.get('name')

'India'

In [23]:
del d1["City"]

In [24]:
d1

{'id': 101, 'name': 'India', 'Age': 200}

In [25]:
s1 = {1,2,3,5,6,7,8}
s2 = {4,5,3,12}


In [26]:
s1.union(s2)

{1, 2, 3, 4, 5, 6, 7, 8, 12}

In [27]:
s1.intersection(s2)

{3, 5}

In [30]:
# List Comprehension - without
data = [23,14,56,72,90]
new_data = []
for x in data:
    if x%2==0:
        new_data.append(x)
new_data

[14, 56, 72, 90]

In [31]:
# If List Comprehension used
data1 = [x for x in data if x%2==0]
data1

[14, 56, 72, 90]

In [32]:
pip install pandas numpy matplotlib seaborn


[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [2]:
data = [23,14,56,72,90]
np.mean(data)

np.float64(51.0)

In [3]:
np.max(data)

np.int64(90)

In [4]:
a = [1,3,5,6]
b = [4,5,6,7]
arr1 = np.array(a)
arr2 = np.array(b)

In [5]:
arr1

array([1, 3, 5, 6])

In [6]:
arr2

array([4, 5, 6, 7])

In [7]:
arr1 * arr2

array([ 4, 15, 30, 42])

In [8]:
arr1.shape
arr1.ndim
arr1.dtype

dtype('int64')

In [10]:
arr3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr3.ndim

2

In [13]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [15]:
np.random.randint(10,100,5)

array([79, 90, 46, 39, 31], dtype=int32)

In [16]:
np.random.uniform(10,100,10)

array([84.16563993, 84.95090421, 73.22149234, 41.83046804, 66.49497474,
       23.78707832, 44.80476488, 22.01756024, 16.53917806, 13.34045296])

In [17]:
np.random.rand(10)

array([0.70266477, 0.64976232, 0.46424436, 0.64660082, 0.87476019,
       0.76823216, 0.01290666, 0.07357239, 0.81690698, 0.96467046])

In [18]:
np.random.randint(10,100,12).reshape(4,3)

array([[60, 26, 85],
       [54, 66, 48],
       [86, 27, 44],
       [94, 56, 54]], dtype=int32)

In [19]:
r =45.7
np.floor(r)

np.float64(45.0)

In [20]:
np.ceil(r)

np.float64(46.0)

In [22]:
z = np.random.randint(100)
z

75

In [23]:
np.percentile(z, 75)

np.float64(75.0)

In [24]:
import pandas as pd

In [39]:
renewable_sources =["Solar", "Wind", "Hydro", "Biomass", "Geothermal"]

data={
    "Project":['Solar Farm', 'Wind turbine', 'Hydropower', 'Solar Roof', 'Geothermal Plant'],
    "Technology":['Solar','Wind','Hydro','Solar','Geothermal'],
    "Capacity (MW)":[150,300,200,50,100],
    "Cost (millions $)": [200,400,350,100,250],
    "Location":["California", "Texas", "Washington", "Nevada", "chicago"],
    "Completion Year": [2023,2024,2022,2025,2023]
}

In [40]:
# create a pandas series for renewable energy sources
renewable_series = pd.Series(renewable_sources)
print("Renewable Energy SOurces are: ")
print(renewable_series)

Renewable Energy SOurces are: 
0         Solar
1          Wind
2         Hydro
3       Biomass
4    Geothermal
dtype: object


In [41]:
# create a dataframe green technology projects
df = pd.DataFrame(data)
print("Green Tech projects DataFrames: ")
df

Green Tech projects DataFrames: 


Project  Technology  Capacity (MW)  Cost (millions $)    Location  \
0        Solar Farm       Solar            150                200  California   
1      Wind turbine        Wind            300                400       Texas   
2        Hydropower       Hydro            200                350  Washington   
3        Solar Roof       Solar             50                100      Nevada   
4  Geothermal Plant  Geothermal            100                250     chicago   

   Completion Year  
0             2023  
1             2024  
2             2022  
3             2025  
4             2023

In [42]:
df['Project']

0          Solar Farm
1        Wind turbine
2          Hydropower
3          Solar Roof
4    Geothermal Plant
Name: Project, dtype: object

In [43]:
df['Location']

0    California
1         Texas
2    Washington
3        Nevada
4       chicago
Name: Location, dtype: object

In [46]:
# Want to print only high capacity projects (>100 MW)
hcp = df[df['Capacity (MW)'] >100]
hcp

Project Technology  Capacity (MW)  Cost (millions $)    Location  \
0    Solar Farm      Solar            150                200  California   
1  Wind turbine       Wind            300                400       Texas   
2    Hydropower      Hydro            200                350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022

In [49]:
# add new col
df["Cost per MW"] = df["Cost (millions $)"] / df['Capacity (MW)']
df

Project  Technology  Capacity (MW)  Cost (millions $)    Location  \
0        Solar Farm       Solar            150                200  California   
1      Wind turbine        Wind            300                400       Texas   
2        Hydropower       Hydro            200                350  Washington   
3        Solar Roof       Solar             50                100      Nevada   
4  Geothermal Plant  Geothermal            100                250     chicago   

   Completion Year  Cost per MW  
0             2023     1.333333  
1             2024     1.333333  
2             2022     1.750000  
3             2025     2.000000  
4             2023     2.500000

In [53]:
# Aggregation
total_capacity = df['Capacity (MW)'].sum()
total_cost = df['Cost (millions $)'].sum()
print("The total capacity of all the projects are: ",total_capacity, "MW")
print("The total cost of  the projects are: ",total_cost, "$")

The total capacity of all the projects are:  800 MW
The total cost of  the projects are:  1300 $


In [60]:
# Grouping of data
grouped_data = df.groupby("Technology")["Capacity (MW)"].sum()
grouped_data

Technology
Geothermal    100
Hydro         200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64